### ISSUE TITLE
Is this lib working with latest versions of Kismet?

### ISSUE THREAD

**Issue by JonnyBGod** [WarheadsSE/node-kismet#2]
I am trying to use this lib in my project but not receiving any messages apart from "TIME" messages.

I am using similar code as in ./bin/rough.js

output:

```
connected!
2016-09-26T17:53:58.000Z
2016-09-26T17:53:59.000Z
2016-09-26T17:54:00.000Z
2016-09-26T17:54:01.000Z
```

Looking at kismet client everything is looking fine.

Any idea?

**Comment by WarheadsSE** [comment]
Which things have you subscribed to?

**Comment by JonnyBGod** [comment]
```
kismet.subscribe('bssid', ['bssid', 'manuf', 'channel', 'type'], function(had_error, message) {
        console.log('bssid - ' + message);
    });
    kismet.subscribe('ssid', ['ssid', 'mac', 'cryptset', 'type', 'packets'], function(had_error, message) {
        console.log('ssid - ' + message);
    });
    kismet.subscribe('client', ['bssid', 'mac', 'type', 'signal_dbm', 'manuf'], function(had_error, message) {
        console.log('client - ' + message);
    });
```

**Comment by JonnyBGod** [comment]
Would it be due to source address?

I want to receive all messages from all detected devices.

**Comment by WarheadsSE** [comment]
The source address only tells the Kismet library what IP address to connect to the running instance of Kismet from. E.g. connect 127.0.0.1 from 127.0.0.1, as per default security settings.

**Comment by JonnyBGod** [comment]
Yes just realised that.

https://www.dropbox.com/s/go2xif5v5sj2lh7/Screenshot%202016-09-26%2019.20.23.png?dl=0

That is my current console screenshot. I removed time logs and is running for 10 minutes now.

**Comment by WarheadsSE** [comment]
Give me a while, I will need to get some things sorted to replicate a live environment.

**Comment by JonnyBGod** [comment]
sure.
For your reference here is the relevant code: https://gist.github.com/JonnyBGod/f59c38c6505f6fb5e89a224924473332

**Comment by tur-ing** [comment]
Same here, any news? Thanks!

**Comment by WarheadsSE** [comment]
Just to make sure I have everything in line, can you both provide me the versions in use? 
- node
- kismet

**Comment by tur-ing** [comment]
node: v6.6.0
kismet: Kismet 2013-03-R0

**Comment by tur-ing** [comment]
@WarheadsSE Do you have a running example app?

**Comment by WarheadsSE** [comment]
@tur-ing I haven't used this myself in some time. I will, however, replicate the environment and try it myself as soon as I have time.

**Comment by tur-ing** [comment]
@WarheadsSE Great, thank you! Please tell me if I can support you anyway.

**Comment by JonnyBGod** [comment]
node: v6.6.0
Kismet-2016-07-R1
Raspberry Pi 3
Laster Raspbian

**Comment by WarheadsSE** [comment]
Okay, I have just started up, and after _configuring Kismet_, I had no issues
- nodejs 6.7.0-1
- kismet 2016_07_R1
- x86_64 Arch Linux on Skylake w/ Intel 8260 A/C

As a tip: make sure your device of choice is not using or attempting to configure your wireless interface.

**Comment by tur-ing** [comment]
@WarheadsSE Could you provide me your Node.js app for testing? I guess I have some bad configuration or programing error ...

**Comment by WarheadsSE** [comment]
@tur-ing , well .. I have. `bin/rough.js`

**Comment by tur-ing** [comment]
@WarheadsSE I think you last tip is important ... looks like the wpa supplicant tries to configure the wlan adapter. I will try to solve the problem and get back as soon as I have more information

**Comment by WarheadsSE** [comment]
#pebkac :+1:  :taco:
